export const PLAY_SONG = 'PLAY_SONG';
export const PAUSE_SONG = 'PAUSE_SONG';
export const NEXT_SONG = 'NEXT_SONG';
export const PREVIOUS_SONG = 'PREVIOUS_SONG';
export const HANDLE_VOLUME = 'HANDLE_VOLUME';
export const SET_AUDIO = 'SET_AUDIO';
export const SET_PROGRESS = 'SET_PROGRESS';
export const SET_MUTE = 'SET_MUTE';
export const SET_TRACKLIST = 'SET_TRACKLIST';
export const TOOGLE_PLAYLIST = 'TOOGLE_PLAYLIST';
export const HANDLE_PLAYLIST = 'HANDLE_PLAYLIST';

export const SEARCH_PLAYLIST = 'SEARCH_PLAYLIST';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';

export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';
export const SET_TOKEN = 'SET_TOKEN';
//Fetch categories actionTypes
export const FETCH_CATEGORIES_SUCCEDED = 'FETCH_CATEGORIES_SUCCEDED';
export const FETCH_CATEGORIES_REQUESTED = 'FETCH_CATEGORIES_REQUESTED';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_HOME_SUCCEDED = 'FETCH_HOME_SUCCEDED';
export const FETCH_HOME_REQUESTED = 'FETCH_HOME_REQUESTED';
export const FETCH_HOME_FAILED = 'FETCH_HOME_FAILED';

export const FETCH_LISTOFPLAYLIST_REQUESTED = 'FETCH_LISTOFPLAYLIST_REQUESTED';
export const FETCH_LISTOFPLAYLIST_SUCCEDED = 'FETCH_LISTOFPLAYLIST_SUCCEDED';
export const FETCH_LISTOFPLAYLIST_FAILED = 'FETCH_LISTOFPLAYLIST_FAILED';

export const FETCH_PLAYLIST_REQUESTED = 'FETCH_PLAYLIST_REQUESTED';
export const FETCH_PLAYLIST_SUCCEDED = 'FETCH_PLAYLIST_SUCCEDED';
export const FETCH_PLAYLIST_FAILED = 'FETCH_PLAYLIST_FAILED';
